# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/kisanmandi
spring.data.mongodb.database=kisanmandi

# JWT
jwt.secret=kisanmandi_super_secret_key_2024_do_not_share
jwt.expiration=86400000

# App name
spring.application.name=kisan-mandi-api

# Disable Spring Security default login page for now
spring.security.user.name=admin
spring.security.user.password=admin123

# File upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Show MongoDB queries in console (helpful for debugging)
logging.level.org.springframework.data.mongodb=DEBUG

# Email Configuration ? Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ritiksinghpk129@gmail.com
spring.mail.password=bikkawfjqkxnxqaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true